baseurl: 'https://lydemann.github.io/blog.lydemann.com/'
languageCode: en
publishDir: docs
title: Christian Lüdemann's blog
theme: hugo-theme-cactus-plus
googleAnalytics: your_google_analytics_code
hasCJKLanguage: true
params:
  name: Christian Lüdemann's blog
  description: Technical blog
  bio:
  twitter: your_twitter
  enableRSS: false
  disqusShortname: lydemann
  enableDisqus: false
  duoshuoShortname: your_duoshuo_short_name
  enableDuoshuo: false
  enableGithubIssuesTips: false
  enableGoogleAnalytics: false
  enableBaiduAnalytics: false
  baiduAnalytics: your_baidu_tongji_code
  customCSS: []
  customJS: []
  home: ''
  about: ''
  category: "Categories"
  archive: 'Posts'
  olderPosts: ''
  newerPosts: ''
  readMore: ''
  copyright: ''
  aboutAuthor: I am so interesting.
  tweet: ''
  share: ''
  title404: 'Page not found'
  subtitle404: ''
  iconFont: font-awesome
  socialIconStyle: ''
social:
  github-square: 'https://github.com/lydemann'
