baseurl: 'https://blog.christianlydemann.com/'
languageCode: en
publishDir: docs
title: Christian Lüdemann's blog
theme: hugo-theme-cactus-plus
googleAnalytics: UA-54304486-2
hasCJKLanguage: true
params:
  name: Christian Lüdemann's blog
  description: Technical blog
  bio:
  twitter: your_twitter
  enableRSS: false
  disqusShortname: blog-christianlydemann-com
  enableDisqus: true
  duoshuoShortname: your_duoshuo_short_name
  enableDuoshuo: false
  enableGithubIssuesTips: false
  enableGoogleAnalytics: true
  enableBaiduAnalytics: false
  baiduAnalytics: your_baidu_tongji_code
  customCSS: []
  customJS: []
  home: ''
  about: ''
  category: "Categories"
  archive: 'Posts'
  olderPosts: ''
  newerPosts: ''
  readMore: ''
  copyright: ''
  aboutAuthor: ''
  tweet: ''
  share: ''
  title404: 'Page not found'
  subtitle404: ''
  iconFont: font-awesome
  socialIconStyle: ''
social:
  github-square: 'https://github.com/lydemann'
