baseurl: 'https://lydemann.github.io/blog.lydemann.com/'
languageCode: en
title: Christian Lüdemann's blog
theme: hugo-theme-cactus-plus
googleAnalytics: your_google_analytics_code
hasCJKLanguage: true
params:
  name: Christian Lüdemann's blog
  description: Technical blog
  bio: Blog biology
  twitter: your_twitter
  enableRSS: false
  disqusShortname: lydemann
  enableDisqus: true
  duoshuoShortname: your_duoshuo_short_name
  enableDuoshuo: false
  enableGithubIssuesTips: true
  enableGoogleAnalytics: false
  enableBaiduAnalytics: false
  baiduAnalytics: your_baidu_tongji_code
  customCSS: []
  customJS: []
  home: ''
  about: ''
  archive: ''
  subscribe: ''
  tags: ''
  olderPosts: ''
  newerPosts: ''
  readMore: ''
  copyright: ''
  aboutAuthor: I am so interesting.
  tweet: ''
  share: ''
  title404: ''
  subtitle404: ''
  iconFont: font-awesome
  socialIconStyle: ''
social:
  github-square: 'https://github.com/lydemann'
